name: Run PR Checks

on:
  push:
    branches:
      - master
      - fork
      - "feature/**"

  pull_request:
    branches:
      - master
      - fork
      - "feature/**"

jobs:
  prcheck:
    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: ci
      CHALICE_TEST_EXTENDED_PACKAGING: true
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install-dev-deps
      - name: Run PRCheck
        run: make prcheck

  cdktests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: actions/setup-python@v6
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt --upgrade --upgrade-strategy eager -e .[cdkv2]
      - name: Run CDK tests
        run: python -m pytest tests/functional/cdk
